version: "3"
services:
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      dockerfile: Dockerfile

  node:
    image: node:16-alpine
    container_name: api_node
    working_dir: /var/api
    command: sh -c "npm install && npm run dev"
    ports:
      - 8080:3000
    environment:
      PORT: 3000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: app_db
    volumes:
      - .:/var/api

  database:
    image: postgres:alpine
    container_name: api_postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: app_db
